---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: secret-mysql
  namespace: database
spec:
  encryptedData:
    password: AgAGsirEQoVStzg4B9KObS6AG0JIWcGLa0l2eKg0UerwdBIsQDHU1/agg5J55OiTDVTRritR1e7ZsP4BYsw7FskLgByoRqZwWZKwVyMlEtEudCKaD6OQUpi4s7WDhqgBGTGDOJH8N9zLRTtu1W0tZ2KM4jWdPag+FC10+2j2hMmjaMYhZwNoaKFvDPXHdZbh+2n3Mk+CqbDB5+g3Hzr54jyroVxHC2ywnpdAsczz/UTfmtpQSLwzWIKaJQxPkNc1PISa4wY3Ix1JMr8Z3MdfEYJ7TCzj4T6BKcEb8lUioUQXOCOEMclZaaoG6jUr+iTEwYnNXDDPjovOwyg3aOr32EVCplGml1yqEq+vLkrb7WJKr6hHvYF/KryOi1SFO9ijnENd/9bWGgW3VoNYEidAiXMEYASCegGBqcg58EJrzuA1s0TFRKKADXzQcv/FTmwlU9d1DjFh0SedMDXcloS4x2Rf6Cgrpaf+S+m6blH2C9fQyu4AU3g6ojQ1XKCu7hRgaVBqaayp1u1WAP3ZGa1aNKdSPLLfJkd/aARyZdlWD7cnEobTSBv8lQYM0Bi9huRqpOjGh7rx4MAOTdIpXujkOskMalwEMBDFc5ivrlu+YCiSi0PqHp26Y+mPT/MjOAxJq1oOJgQ5PHMeNEFkSPC7zzTBc+Zz6hlb4ywws3qhnGwbjX3/qE/Ql3JRZAYcBMxdMWxA/KEXtaKm0jKqFy6xk/dIyapqlbQIz1MI
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: secret-mysql
      namespace: database
